Tensors are Multi dimensional arrays

In [2]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(2)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
tensor_one_d = tf.constant([1,2,3])
tensor_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [4]:
tensor_two_d = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor_two_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [89]:
tensor_three_d = tf.constant([
                              [[1.2,2,3],[4,5,6],[7,8,9]],
                              [[1,2,3],[4,5,6],[7,8,9]],
                              [[1,2,3],[4,5,6],[7,8,9]]
                            ])
tensor_three_d

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1.2, 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]], dtype=float32)>

In [14]:
tensor_four_d = tf.constant([
                              [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],
                              [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],
                              [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
                            ])
tensor_four_d

<tf.Tensor: shape=(3, 3, 3, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])>

In [15]:
tensor_string = tf.constant(['hello', 'world'])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [17]:
np_array = np.array([1,2,4])
np_array

array([1, 2, 4])

In [19]:
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

## Built-in functions

In [42]:
## eye, fill, ones, ones_like, zeros, zeros_like
eye_tensor = tf.eye(num_rows=3,num_columns=None,batch_shape=[2,])
print('identity matrix: ', eye_tensor)

ones_tensor = tf.ones([3,2], dtype=tf.dtypes.int16)
print('ones matrix: ', ones_tensor)

zeros_tensor = tf.zeros_like(ones_tensor, dtype=tf.dtypes.float16)
print('zeros like matrix: ', zeros_tensor)

identity matrix:  tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)
ones matrix:  tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int16)
zeros like matrix:  tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float16)


In [43]:
## size, shape and rank returns tensors
print('rank: ', tf.rank(tensor_two_d))
print('shape: ', tensor_two_d.shape, tf.shape(tensor_two_d))
print('size: ', tf.size(tensor_two_d))

rank:  tf.Tensor(2, shape=(), dtype=int32)
shape:  (3, 3) tf.Tensor([3 3], shape=(2,), dtype=int32)
size:  tf.Tensor(9, shape=(), dtype=int32)


In [45]:
## random normal distribution
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=0.5,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.12517582, -0.9978536 ],
       [ 0.639383  ,  0.3338684 ],
       [ 0.21334286,  0.3815008 ]], dtype=float32)>

In [50]:
## random uniform distribution
random_tensor = tf.random.uniform(
    [3,],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.float32,
    seed=10,
    name=None
)

random_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([650.0373 , 419.1531 , 840.42957], dtype=float32)>

## Indexing

In [57]:
tensor_indexed = tf.constant([2,5,3,7,10,12,15,17,19])
print(tensor_indexed)
print(tensor_indexed[3])  # idx
print(tensor_indexed[:3]) # max idx
print(tensor_indexed[3:5])  # min idx
print(tensor_indexed[3:8:2]) # shape

tf.Tensor([ 2  5  3  7 10 12 15 17 19], shape=(9,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([2 5 3], shape=(3,), dtype=int32)
tf.Tensor([ 7 10], shape=(2,), dtype=int32)
tf.Tensor([ 7 12 17], shape=(3,), dtype=int32)


In [64]:
print(tensor_two_d[1:3, 1:3]) # two D indexing
print(tensor_three_d[2:3, ..., 1:3]) # three D indexing

tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[[2 3]
   [5 6]
   [8 9]]

  [[2 3]
   [5 6]
   [8 9]]

  [[2 3]
   [5 6]
   [8 9]]]], shape=(1, 3, 3, 2), dtype=int32)


## Math Operations

In [78]:
print(tf.abs(tf.constant(-3)))
print(tf.abs(tf.constant(-3 + 4j)))
tf.sqrt(3.3)  # int not allowed

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(5.0, shape=(), dtype=float64)


<tf.Tensor: shape=(), dtype=float32, numpy=1.8165902>

In [4]:
x_1 = tf.constant([[1,2,3,4,5],])
x_2 = tf.constant([5])

print(tf.math.add(x_1, x_2))
print(tf.math.multiply(x_1, x_2))
print(tf.math.multiply(x_1, tf.constant([[2], [5]])))

tf.Tensor([[ 6  7  8  9 10]], shape=(1, 5), dtype=int32)
tf.Tensor([[ 5 10 15 20 25]], shape=(1, 5), dtype=int32)
tf.Tensor(
[[ 2  4  6  8 10]
 [ 5 10 15 20 25]], shape=(2, 5), dtype=int32)


In [14]:
x_argmax = tf.constant([[1,2,33,4,50], [11,231,31,41,5], [0,21,31,341,35]])
print(tf.math.argmax(x_argmax))
print(tf.math.argmax(x_argmax, 0))  # axis = 0
print(tf.math.argmax(x_argmax, 1))  # axis = 1
print(tf.math.argmin(x_argmax))
print(tf.math.argmin(x_argmax, 0))  # axis = 0
print(tf.math.argmin(x_argmax, 1))  # axis = 1

tf.Tensor([1 1 0 2 0], shape=(5,), dtype=int64)
tf.Tensor([1 1 0 2 0], shape=(5,), dtype=int64)
tf.Tensor([4 1 3], shape=(3,), dtype=int64)
tf.Tensor([2 0 1 0 1], shape=(5,), dtype=int64)
tf.Tensor([2 0 1 0 1], shape=(5,), dtype=int64)
tf.Tensor([0 4 0], shape=(3,), dtype=int64)


In [32]:
x = tf.constant([[1,3],[1,2]])
y = tf.constant([[1,3],[1,0]])

print(tf.math.equal(x, y))
print(tf.pow(x, y))
print(tf.math.reduce_sum(x, axis=None, keepdims=False, name=None))
print(tf.math.reduce_max(x, axis=1, keepdims=False, name=None)) # axis-x
print(tf.math.reduce_min(y, axis=0, keepdims=False, name=None)) # axis-y
print(tf.math.reduce_mean(x, axis=0, keepdims=False, name=None))

tf.Tensor(
[[ True  True]
 [ True False]], shape=(2, 2), dtype=bool)
tf.Tensor(
[[ 1 27]
 [ 1  1]], shape=(2, 2), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor([1 0], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [34]:
tf.math.top_k(y, k=2)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 1],
       [1, 0]])>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]])>)

## Linear Algebra

In [37]:
tf.linalg.matmul(x, y, 
                 transpose_a=False, transpose_b=False, 
                 adjoint_a=False, adjoint_b=False,
                 a_is_sparse=False, b_is_sparse=False, 
                 output_type=None, name=None
                )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [3, 3]])>

In [41]:
print("element wise: ", x*y)
print("matrix mul: ", x@y)

tf.transpose(x)

element wise:  tf.Tensor(
[[1 9]
 [1 0]], shape=(2, 2), dtype=int32)
matrix mul:  tf.Tensor(
[[4 3]
 [3 3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [3, 2]])>

In [55]:
x_3_d = tf.constant([[[1,3],[1,2]], [[0,3],[2,1]], [[3,1],[1,0]]])
y_3_d = tf.constant([[[3,4],[0,2]], [[3,2],[0,3]],[[2,4],[3,2]]])

print('x: ', x_3_d.shape, " y: ", y_3_d.shape)
print(x_3_d*y_3_d)
print(x_3_d@y_3_d)

x:  (3, 2, 2)  y:  (3, 2, 2)
tf.Tensor(
[[[ 3 12]
  [ 0  4]]

 [[ 0  6]
  [ 0  3]]

 [[ 6  4]
  [ 3  0]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 3 10]
  [ 3  8]]

 [[ 0  9]
  [ 6  7]]

 [[ 9 14]
  [ 2  4]]], shape=(3, 2, 2), dtype=int32)


In [62]:
## (lower < 0 or m-n <= lower) and (upper < 0 or m-n <= upper)
## m -- rows, n -- columns
print(tf.linalg.band_part(x_3_d, 0, 0))  # diagnol
print(tf.linalg.band_part(x_3_d, -1, 0))  # lower triangular
print(tf.linalg.band_part(x_3_d, 0, -1))  # upper triangular

tf.Tensor(
[[[1 0]
  [0 2]]

 [[0 0]
  [0 1]]

 [[3 0]
  [0 0]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[1 0]
  [1 2]]

 [[0 0]
  [2 1]]

 [[3 0]
  [1 0]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[1 3]
  [0 2]]

 [[0 3]
  [0 1]]

 [[3 1]
  [0 0]]], shape=(3, 2, 2), dtype=int32)


In [65]:
sq_x = tf.constant([[1,3],[1,2]], dtype='float32')
tf.linalg.inv(sq_x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.,  3.],
       [ 1., -1.]], dtype=float32)>

In [67]:
s, u, v = tf.linalg.svd(sq_x)
print('singular values: ', s)
print('left singular vectors: ', u)
print('right singular vectors: ', v)

singular values:  tf.Tensor([3.8643284  0.25877714], shape=(2,), dtype=float32)
left singular vectors:  tf.Tensor(
[[ 0.8174155 -0.5760485]
 [ 0.5760485  0.8174155]], shape=(2, 2), dtype=float32)
right singular vectors:  tf.Tensor(
[[ 0.36059666  0.9327218 ]
 [ 0.9327218  -0.36059666]], shape=(2, 2), dtype=float32)


In [80]:
A = tf.constant([[2,6,5,2],[2,-2,2,3],[1,2,3,4]])  # i,j
B = tf.constant([[2,6,5,2,0],[2,-2,2,3,0],[1,2,3,4,0],[1,2,3,4,5]])  # j,k

print("matmul: ", tf.linalg.matmul(A,B))
print("einsum: ", tf.einsum("ij,jk -> ik",A,B))
print("transpose using einsum: ", tf.einsum("ij -> ji",A))
print("element wise using multiplication einsum: ", tf.einsum("ij, ij -> ji",A, A))
print("sum of elements: ", tf.einsum("ij ->", A))
print("sum of elements along axis: ", tf.einsum("ij -> j", A))

matmul:  tf.Tensor(
[[23 14 43 50 10]
 [ 5 26 21 18 15]
 [13 16 30 36 20]], shape=(3, 5), dtype=int32)
einsum:  tf.Tensor(
[[23 14 43 50 10]
 [ 5 26 21 18 15]
 [13 16 30 36 20]], shape=(3, 5), dtype=int32)
transpose using einsum:  tf.Tensor(
[[ 2  2  1]
 [ 6 -2  2]
 [ 5  2  3]
 [ 2  3  4]], shape=(4, 3), dtype=int32)
element wise using multiplication einsum:  tf.Tensor(
[[ 4  4  1]
 [36  4  4]
 [25  4  9]
 [ 4  9 16]], shape=(4, 3), dtype=int32)
sum of elements:  tf.Tensor(30, shape=(), dtype=int32)
sum of elements along axis:  tf.Tensor([ 5  6 10  9], shape=(4,), dtype=int32)


In [85]:
## Attention all you need (paper)

Q = tf.random.normal([32,64,512])
K = tf.random.normal([32,128,512])

tf.einsum("bqm,bkm -> bqk", Q, K).shape

TensorShape([32, 64, 128])

In [88]:
## Reformer: The efficient transformer (paper)

A = tf.random.normal([2,4,4,2])
B = tf.random.normal([2,4,4,1])

print(tf.einsum("bcik,bcij -> bckj", B, A).shape)
print(tf.linalg.matmul(tf.linalg.matrix_transpose(B, (0,1,2,4,3)), A).shape)

(2, 4, 1, 2)
(2, 4, 1, 2)


## Common tensorflow functions

In [104]:
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis=0).shape) # expand dimensions of matrix
print(tf.expand_dims(tensor_three_d, axis=1).shape) # expand dimensions of matrix

x_squeezed = tf.constant([[[[1, 2, 3]]]])
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis=i)
  print(x_squeezed.shape) # squeeze dimensions of matrix

x_reshape = tf.constant([[1,2,3,4], [5,6,7,8]])
print(tf.reshape(x_reshape, [8]))
print(tf.reshape(x_reshape, [4,2])) # note: not a transpose
print(tf.reshape(x_reshape, [4,-1])) # note: not a transpose

(3, 3, 3)
(1, 3, 3, 3)
(3, 1, 3, 3)
(1, 1, 3)
(1, 3)
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [108]:
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[11,12,13],[14,15,16]])

print("axis=0: ", tf.concat([t1,t2], axis=0))
print("axis=1: ", tf.concat([t1,t2], axis=1))

axis=0:  tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]], shape=(4, 3), dtype=int32)
axis=1:  tf.Tensor(
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]], shape=(2, 6), dtype=int32)


In [116]:
print("axis=0: ", tf.stack([t1, t2], axis=0).shape)
print("axis=1: ", tf.stack([t1, t2], axis=1).shape)
print("axis=2: ", tf.stack([t1, t2], axis=2).shape)
print("axis=2 t1,t2,t1: ", tf.stack([t1, t2, t1], axis=0).shape)

axis=0:  (2, 2, 3)
axis=1:  (2, 2, 3)
axis=2:  (2, 3, 2)
axis=2 t1,t2,t1:  (3, 2, 3)


In [122]:
paddings = tf.constant([[1,2],[3,4]])
print(tf.pad(t1, paddings, 'CONSTANT', constant_values=0))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0 0]
 [0 0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]], shape=(5, 10), dtype=int32)


In [127]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4'])
print(params[1:3].numpy())
print(tf.gather(params, tf.range(1,3)).numpy())

[b'p1' b'p2']
[b'p1' b'p2']


In [134]:
indices1 = [[0], [1]]
indices2 = [[2, 1]]
params = [['a', 'b'], ['c', 'd'], ['e', 'f']]
print(tf.gather_nd(params, indices1))
print(tf.gather_nd(params, indices2))

tf.Tensor(
[[b'a' b'b']
 [b'c' b'd']], shape=(2, 2), dtype=string)
tf.Tensor([b'f'], shape=(1,), dtype=string)


### Ragged tensors: Rectangular shape

In [141]:
r1 = [[1,2,0], [3], [1,5,6,7,8,9],[1,2]]
tensor_ragged = tf.ragged.constant(r1)
print(tensor_ragged.shape)
print(tf.ragged.boolean_mask(tensor_ragged, tf.ragged.constant([True, True, False,True])))


(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 2]]>


In [146]:
gen_ragged = tf.RaggedTensor.from_row_lengths(values=[3,1,4,1,5,9,2,6], row_lengths=[4,0,3,1,])
print(gen_ragged)
print(gen_ragged.shape)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6]]>
(4, None)


### Sparse tensors

In [149]:
tensor_sparse = tf.sparse.SparseTensor(indices=[[1,1],[3,4]], values=[11,56], dense_shape=[5,6])
print("tensor_sparse: ", tensor_sparse)
print("dense_sparse: ", tf.sparse.to_dense(tensor_sparse))

tensor_sparse:  SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))
dense_sparse:  tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 56  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


### String tensors

In [154]:
tensor_string = tf.constant(['hi', 'hello'])
print(tensor_string)
print(tf.strings.join(tensor_string, separator=", "))
print(tf.strings.upper(tensor_string))

tf.Tensor([b'hi' b'hello'], shape=(2,), dtype=string)
tf.Tensor(b'hi, hello', shape=(), dtype=string)
tf.Tensor([b'HI' b'HELLO'], shape=(2,), dtype=string)


## Tensor variables

In [156]:
x = tf.constant([1,2])
x_var = tf.Variable([1,2])
x_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [159]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2])>

In [164]:
with tf.device('CPU:0'):
    x_1 = tf.constant([1,2,3])
    x_2 = tf.Variable([2])

with tf.device('GPU:0'):
    x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([2])> /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([3 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
